name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubunt-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies 
        rum: npm ci --force

      - name: Build Storybook 
        run: npm run buils-storybook

      - name: Deploy Storybook
        run: npm run deploy-storybook -- --ci --existing-outpout-dir=storybook-statics
        env:
          GH-TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}